/** @file SineTable.cpp
 *  @date Oct 2, 2010
 */
#include "SineTable.h"

int16_t SineTable::getSine(uint16_t div) {
  if (div <= SINE_TABLE_DIVISIONS)
    return _sineTable[div];
  else if (div <= (SINE_TABLE_DIVISIONS*2))
    return _sineTable[(SINE_TABLE_DIVISIONS*2)-div];
  else if (div <= SINE_TABLE_DIVISIONS*3)
    return -_sineTable[div-(SINE_TABLE_DIVISIONS*2)];
  else
    return -_sineTable[(SINE_TABLE_DIVISIONS*4)-div];
}

/**
 * This is generated by scripts/SineTableGen.py
 *
 * Note that this is 1/4 of the sine wave, the rest of the wave is calculated by mirroring
 * and flipping the numbers. This yields a range of -255 to 255.
 */
uint8_t SineTable::_sineTable[] = {
  0,   13,  25,  37,  50,  62,  74,  86,
  98,  109, 120, 131, 142, 152, 162, 171,
  180, 189, 197, 205, 212, 219, 225, 231,
  236, 240, 244, 247, 250, 252, 254, 255,
  255
};
